version: "3"
services:
  app:
    container_name: my-app
    build: .
    environment:
      - NAME=Ilya
    networks:
      - app-network

  chrome:
    image: selenium/node-chrome:4.0.0-beta-1-prerelease-20201208
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    scale: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=docker_app
    ports:
      - "5900"
    networks:
      - app-network

  firefox:
    image: selenium/node-firefox:4.0.0-beta-1-prerelease-20201208
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    scale: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"
    networks:
      - app-network

  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-prerelease-20201208
    container_name: selenium-hub
    networks:
      - app-network
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  app-network:
    driver: bridge
